version: "3.8"

services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 3987:3987
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"

  api:
    image: node-image
    container_name: video-list-api
    pull_policy: build
    depends_on:
      - reverse-proxy
    build:
      context: .
      args:
        PROJECT: api
    ports:
      - 3000:3000
    env_file:
      - stack.env
