version: "3.8"

services:
  api:
    container_name: video-list-api
    restart: unless-stopped
    pull_policy: build
    build:
      context: .
      args:
        PROJECT: api
    ports:
      - 3000:3000
    healthcheck:
      test: curl --fail http://localhost:3000/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
