version: "3.8"

services:
  api:
    container_name: video-list-api
    restart: always
    networks:
      - app_network
    build:
      context: .
      args:
        PROJECT: api
    ports:
      - 3000:3000
    env_file:
      - stack.env

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
