/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PlaylistsPlaylistIDVideoIDImport } from './routes/playlists/$playlistID/$videoID'

// Create Virtual Routes

const PlaylistsPlaylistIDIndexLazyImport = createFileRoute(
  '/playlists/$playlistID/',
)()
const PlaylistsPlaylistIDEditLazyImport = createFileRoute(
  '/playlists/$playlistID/edit',
)()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistsPlaylistIDIndexLazyRoute =
  PlaylistsPlaylistIDIndexLazyImport.update({
    path: '/playlists/$playlistID/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/playlists/$playlistID/index.lazy').then((d) => d.Route),
  )

const PlaylistsPlaylistIDEditLazyRoute =
  PlaylistsPlaylistIDEditLazyImport.update({
    path: '/playlists/$playlistID/edit',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/playlists/$playlistID/edit.lazy').then((d) => d.Route),
  )

const PlaylistsPlaylistIDVideoIDRoute = PlaylistsPlaylistIDVideoIDImport.update(
  {
    path: '/playlists/$playlistID/$videoID',
    getParentRoute: () => rootRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/playlists/$playlistID/$videoID': {
      id: '/playlists/$playlistID/$videoID'
      path: '/playlists/$playlistID/$videoID'
      fullPath: '/playlists/$playlistID/$videoID'
      preLoaderRoute: typeof PlaylistsPlaylistIDVideoIDImport
      parentRoute: typeof rootRoute
    }
    '/playlists/$playlistID/edit': {
      id: '/playlists/$playlistID/edit'
      path: '/playlists/$playlistID/edit'
      fullPath: '/playlists/$playlistID/edit'
      preLoaderRoute: typeof PlaylistsPlaylistIDEditLazyImport
      parentRoute: typeof rootRoute
    }
    '/playlists/$playlistID/': {
      id: '/playlists/$playlistID/'
      path: '/playlists/$playlistID'
      fullPath: '/playlists/$playlistID'
      preLoaderRoute: typeof PlaylistsPlaylistIDIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PlaylistsPlaylistIDVideoIDRoute,
  PlaylistsPlaylistIDEditLazyRoute,
  PlaylistsPlaylistIDIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/playlists/$playlistID/$videoID",
        "/playlists/$playlistID/edit",
        "/playlists/$playlistID/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/playlists/$playlistID/$videoID": {
      "filePath": "playlists/$playlistID/$videoID.tsx"
    },
    "/playlists/$playlistID/edit": {
      "filePath": "playlists/$playlistID/edit.lazy.tsx"
    },
    "/playlists/$playlistID/": {
      "filePath": "playlists/$playlistID/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
