/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MeImport } from './routes/me'
import { Route as IndexImport } from './routes/index'
import { Route as UserUserIDImport } from './routes/user/$userID'
import { Route as AuthLogoutImport } from './routes/auth/logout'
import { Route as PlaylistPlaylistIDIndexImport } from './routes/playlist/$playlistID/index'
import { Route as PlaylistPlaylistIDPlayImport } from './routes/playlist/$playlistID/play'
import { Route as PlaylistPlaylistIDVideoIDImport } from './routes/playlist/$playlistID/$videoID'
import { Route as AuthGoogleRedirectImport } from './routes/auth/google/redirect'
import { Route as AuthGoogleLoginImport } from './routes/auth/google/login'

// Create/Update Routes

const MeRoute = MeImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UserUserIDRoute = UserUserIDImport.update({
  id: '/user/$userID',
  path: '/user/$userID',
  getParentRoute: () => rootRoute,
} as any)

const AuthLogoutRoute = AuthLogoutImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistPlaylistIDIndexRoute = PlaylistPlaylistIDIndexImport.update({
  id: '/playlist/$playlistID/',
  path: '/playlist/$playlistID/',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistPlaylistIDPlayRoute = PlaylistPlaylistIDPlayImport.update({
  id: '/playlist/$playlistID/play',
  path: '/playlist/$playlistID/play',
  getParentRoute: () => rootRoute,
} as any)

const PlaylistPlaylistIDVideoIDRoute = PlaylistPlaylistIDVideoIDImport.update({
  id: '/playlist/$playlistID/$videoID',
  path: '/playlist/$playlistID/$videoID',
  getParentRoute: () => rootRoute,
} as any)

const AuthGoogleRedirectRoute = AuthGoogleRedirectImport.update({
  id: '/auth/google/redirect',
  path: '/auth/google/redirect',
  getParentRoute: () => rootRoute,
} as any)

const AuthGoogleLoginRoute = AuthGoogleLoginImport.update({
  id: '/auth/google/login',
  path: '/auth/google/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeImport
      parentRoute: typeof rootRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutImport
      parentRoute: typeof rootRoute
    }
    '/user/$userID': {
      id: '/user/$userID'
      path: '/user/$userID'
      fullPath: '/user/$userID'
      preLoaderRoute: typeof UserUserIDImport
      parentRoute: typeof rootRoute
    }
    '/auth/google/login': {
      id: '/auth/google/login'
      path: '/auth/google/login'
      fullPath: '/auth/google/login'
      preLoaderRoute: typeof AuthGoogleLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/google/redirect': {
      id: '/auth/google/redirect'
      path: '/auth/google/redirect'
      fullPath: '/auth/google/redirect'
      preLoaderRoute: typeof AuthGoogleRedirectImport
      parentRoute: typeof rootRoute
    }
    '/playlist/$playlistID/$videoID': {
      id: '/playlist/$playlistID/$videoID'
      path: '/playlist/$playlistID/$videoID'
      fullPath: '/playlist/$playlistID/$videoID'
      preLoaderRoute: typeof PlaylistPlaylistIDVideoIDImport
      parentRoute: typeof rootRoute
    }
    '/playlist/$playlistID/play': {
      id: '/playlist/$playlistID/play'
      path: '/playlist/$playlistID/play'
      fullPath: '/playlist/$playlistID/play'
      preLoaderRoute: typeof PlaylistPlaylistIDPlayImport
      parentRoute: typeof rootRoute
    }
    '/playlist/$playlistID/': {
      id: '/playlist/$playlistID/'
      path: '/playlist/$playlistID'
      fullPath: '/playlist/$playlistID'
      preLoaderRoute: typeof PlaylistPlaylistIDIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/user/$userID': typeof UserUserIDRoute
  '/auth/google/login': typeof AuthGoogleLoginRoute
  '/auth/google/redirect': typeof AuthGoogleRedirectRoute
  '/playlist/$playlistID/$videoID': typeof PlaylistPlaylistIDVideoIDRoute
  '/playlist/$playlistID/play': typeof PlaylistPlaylistIDPlayRoute
  '/playlist/$playlistID': typeof PlaylistPlaylistIDIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/user/$userID': typeof UserUserIDRoute
  '/auth/google/login': typeof AuthGoogleLoginRoute
  '/auth/google/redirect': typeof AuthGoogleRedirectRoute
  '/playlist/$playlistID/$videoID': typeof PlaylistPlaylistIDVideoIDRoute
  '/playlist/$playlistID/play': typeof PlaylistPlaylistIDPlayRoute
  '/playlist/$playlistID': typeof PlaylistPlaylistIDIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/user/$userID': typeof UserUserIDRoute
  '/auth/google/login': typeof AuthGoogleLoginRoute
  '/auth/google/redirect': typeof AuthGoogleRedirectRoute
  '/playlist/$playlistID/$videoID': typeof PlaylistPlaylistIDVideoIDRoute
  '/playlist/$playlistID/play': typeof PlaylistPlaylistIDPlayRoute
  '/playlist/$playlistID/': typeof PlaylistPlaylistIDIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/me'
    | '/auth/logout'
    | '/user/$userID'
    | '/auth/google/login'
    | '/auth/google/redirect'
    | '/playlist/$playlistID/$videoID'
    | '/playlist/$playlistID/play'
    | '/playlist/$playlistID'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/me'
    | '/auth/logout'
    | '/user/$userID'
    | '/auth/google/login'
    | '/auth/google/redirect'
    | '/playlist/$playlistID/$videoID'
    | '/playlist/$playlistID/play'
    | '/playlist/$playlistID'
  id:
    | '__root__'
    | '/'
    | '/me'
    | '/auth/logout'
    | '/user/$userID'
    | '/auth/google/login'
    | '/auth/google/redirect'
    | '/playlist/$playlistID/$videoID'
    | '/playlist/$playlistID/play'
    | '/playlist/$playlistID/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeRoute: typeof MeRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  UserUserIDRoute: typeof UserUserIDRoute
  AuthGoogleLoginRoute: typeof AuthGoogleLoginRoute
  AuthGoogleRedirectRoute: typeof AuthGoogleRedirectRoute
  PlaylistPlaylistIDVideoIDRoute: typeof PlaylistPlaylistIDVideoIDRoute
  PlaylistPlaylistIDPlayRoute: typeof PlaylistPlaylistIDPlayRoute
  PlaylistPlaylistIDIndexRoute: typeof PlaylistPlaylistIDIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeRoute: MeRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  UserUserIDRoute: UserUserIDRoute,
  AuthGoogleLoginRoute: AuthGoogleLoginRoute,
  AuthGoogleRedirectRoute: AuthGoogleRedirectRoute,
  PlaylistPlaylistIDVideoIDRoute: PlaylistPlaylistIDVideoIDRoute,
  PlaylistPlaylistIDPlayRoute: PlaylistPlaylistIDPlayRoute,
  PlaylistPlaylistIDIndexRoute: PlaylistPlaylistIDIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/me",
        "/auth/logout",
        "/user/$userID",
        "/auth/google/login",
        "/auth/google/redirect",
        "/playlist/$playlistID/$videoID",
        "/playlist/$playlistID/play",
        "/playlist/$playlistID/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/me": {
      "filePath": "me.tsx"
    },
    "/auth/logout": {
      "filePath": "auth/logout.tsx"
    },
    "/user/$userID": {
      "filePath": "user/$userID.tsx"
    },
    "/auth/google/login": {
      "filePath": "auth/google/login.tsx"
    },
    "/auth/google/redirect": {
      "filePath": "auth/google/redirect.tsx"
    },
    "/playlist/$playlistID/$videoID": {
      "filePath": "playlist/$playlistID/$videoID.tsx"
    },
    "/playlist/$playlistID/play": {
      "filePath": "playlist/$playlistID/play.tsx"
    },
    "/playlist/$playlistID/": {
      "filePath": "playlist/$playlistID/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
