/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ListsListIDImport } from './routes/lists/$listID'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ListsListIDRoute = ListsListIDImport.update({
  path: '/lists/$listID',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/lists/$listID': {
      id: '/lists/$listID'
      path: '/lists/$listID'
      fullPath: '/lists/$listID'
      preLoaderRoute: typeof ListsListIDImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, ListsListIDRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/lists/$listID"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/lists/$listID": {
      "filePath": "lists/$listID.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
