version: '3.8'

services:
  api:
    container_name: watchlist-api
    build:
      context: ../..   # point to repo root from apps/api folder
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
    labels:
      logging: "promtail"
      job: "watchlist-api"
    depends_on:
      - promtail

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - ./config:/etc/promtail
      - /var/log:/var/log:ro
