version: '3.8'

services:
  api:
    container_name: watchlist-api
    build:
      context: ../..   # point to repo root from apps/api folder
      dockerfile: apps/api/Dockerfile
    ports:
      - "3000:3000"
    labels:
      logging: "promtail"
      job: "watchlist-api"
    depends_on:
      - promtail

  promtail:
    container_name: promtail
    build:
      context: ./promtail
      dockerfile: Dockerfile
    command: -config.file=/etc/promtail/promtail-config.yml
    volumes:
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
